name: fluentbit

on:
  push:
    tags:
      - 'fluentbit-v*.*.*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Public ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: Rewrite release version
        id: version
        run: |
          VERSION=${{ github.ref_name }}
          echo "version=${VERSION#fluentbit-v}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: "./fluentbit/Dockerfile"
          context: "./fluentbit"
          push: true
          tags: ghcr.io/unsafesystems/fluentbit:latest,ghcr.io/unsafesystems/fluentbit:${{steps.version.outputs.version}},public.ecr.aws/m0m7e8y4/fluentbit:latest,public.ecr.aws/m0m7e8y4/fluentbit:${{steps.version.outputs.version}}
          platforms: linux/amd64,linux/arm64